/**
 * Preloaded sample applications for the demo and the Phase 1 acceptance
 * tests. Each sample is form fields + label face image refs (under
 * `/fixtures/images/`, served by Next.js from `public/`).
 *
 * The same data path drives both: the sample picker on the input page
 * (P1-1) hydrates the form from these, and the P1-10 acceptance tests
 * import the same map so the demo path and the test path can never drift.
 *
 * Sample IDs MUST match the mock provider's fixture keys in
 * `lib/provider/mock.ts` so a chosen sample produces a canned extraction
 * for the matching engine to chew on (P1-3, P1-5).
 *
 * Image files in `public/fixtures/images/` were generated by the cola-
 * generator tool (AI synthetic, not applicant PII) and are safe to commit
 * under NFR-4.
 */

import type { BeverageType, FaceKind } from "@/types";

/** Form values an applicant would type — exactly the FormFields shape. */
export type SampleForm = {
  brandName: string;
  fancifulName?: string;
  classType: string;
  alcoholContent: string;
  netContents: string;
  producerName: string;
  producerAddress: string;
  countryOfOrigin?: string;
};

/** One sample face — refers to a bundled image at `/fixtures/images/...`. */
export type SampleFace = {
  kind: FaceKind;
  imageSrc: string;
};

export type Sample = {
  id: string;
  beverageType: BeverageType;
  /** Short label shown in the picker UI. */
  label: string;
  /** One-line description of what this sample exercises. */
  notes: string;
  form: SampleForm;
  faces: SampleFace[];
};

export const SAMPLES: Sample[] = [
  {
    id: "sample-green-001",
    beverageType: "wine",
    label: "Harbor Mist (clean match)",
    notes: "All form fields match the label. Should land in the match lane.",
    form: {
      brandName: "HARBOR MIST",
      fancifulName: "Coastal White",
      classType: "TABLE WINE",
      alcoholContent: "12.5%",
      netContents: "750 ML",
      producerName: "HARBOR MIST CELLARS",
      producerAddress: "123 VINE ST, NAPA CA",
      countryOfOrigin: "USA",
    },
    faces: [
      {
        kind: "front",
        imageSrc: "/fixtures/images/none_001.png",
      },
    ],
  },
  {
    id: "sample-abv-mismatch-001",
    beverageType: "distilled_spirits",
    label: "Old Cedar (ABV mismatch — form 40%, label 45%)",
    notes: "Form says 40%; label shows 45%. Should land in the mismatch lane on the abv field.",
    form: {
      brandName: "OLD CEDAR",
      classType: "KENTUCKY STRAIGHT BOURBON",
      alcoholContent: "40%",
      netContents: "750 ML",
      producerName: "OLD CEDAR DISTILLERY",
      producerAddress: "456 BARREL LN, LOUISVILLE KY",
    },
    faces: [
      {
        kind: "front",
        imageSrc: "/fixtures/images/abv_mismatch_001.png",
      },
    ],
  },
  {
    id: "sample-case-variant-001",
    beverageType: "wine",
    label: "Harbor Mist — case variant (still a match)",
    notes:
      "Form brand is Title Case, label is ALL CAPS — same product, must still MATCH (guards against false positives).",
    form: {
      brandName: "Harbor Mist",
      fancifulName: "Coastal White",
      classType: "TABLE WINE",
      alcoholContent: "12.5%",
      netContents: "750 ML",
      producerName: "HARBOR MIST CELLARS",
      producerAddress: "123 VINE ST, NAPA CA",
      countryOfOrigin: "USA",
    },
    faces: [
      {
        kind: "front",
        imageSrc: "/fixtures/images/case_variant_001.png",
      },
    ],
  },
];

/** Look up one sample by id. */
export function getSample(id: string): Sample | undefined {
  return SAMPLES.find((s) => s.id === id);
}
